name: early-access

on:
  workflow_dispatch:
    inputs:
      currentDevelopmentVersion:
        description: 'The current development version'
        required: true

jobs:
  pre-release-build:
    name: Build Pre-release Artifacts
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        experimental: [ false ]
        include:
          - os: [ macos-latest ]
            experimental: true
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: graalvm/setup-graalvm@v1.3.4
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Login to Container Registry
        if: matrix.os == 'ubuntu-latest' && github.repository == 'wanaku-ai/wanaku'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Create a snapshot build (with container push)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mvn -Dnative -Pdist \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.additional-tags=${{ github.event.inputs.currentDevelopmentVersion }} \
          clean package
      - name: Create a snapshot build
        if: matrix.os != 'ubuntu-latest'
        run: |
          mvn -Dnative -Pdist clean package

  release-to-github-linux:
    name: Release to GitHub (Linux and Common Artifacts)
    needs: pre-release-build
    runs-on: ubuntu-latest
    steps:
      - name: Run JReleaser (Linux)
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.currentDevelopmentVersion }}
          JRELEASER_PROJECT_SNAPSHOT_LABEL: early-access
          JRELEASER_SELECT_CURRENT_PLATFORM: true
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      # Persist logs

      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-release-linux
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

# We need to run this one after the linux one, to prevent jreleaser from dropping the release.
# That is why we set the JRELEASER_OVERWRITE to false
  release-to-github-macos:
    name: Release to GitHub (macOS Binaries)
    needs: release-to-github-linux
    runs-on: ubuntu-latest
    steps:
      - name: Run JReleaser (Linux)
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.currentDevelopmentVersion }}
          JRELEASER_PROJECT_SNAPSHOT_LABEL: early-access
          JRELEASER_SELECT_CURRENT_PLATFORM: true
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_OVERWRITE: false

      # Persist logs

      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-release-macos
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties