name: Deploy Wanaku Dev

on:
  workflow_run:
    workflows: ["Build Main"]
    types:
      - completed

env:
  PROJECTS: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Deploy on the cloud
      run: kubectl apply -f deploy/openshift